import gradio as gr

def linear_search_visual(arr_str, target):
    #Check if list is valid and converts it into list of ints 
    try:
        arr = [int(x.strip()) for x in arr_str.split(",")]
    except:
        return "Error: Make sure the list contains only numbers separated by commas"
    #Same thing with target
    try:
        target = int(target)
    except:
        return "Error: Target must be a number"
    steps = [] #Stores each step

    #Linear search algorithm, compares each value and saves it to steps
    for i in range(len(arr)):
        steps.append(f"Comparing index {i}: value = {arr[i]} and target = {target}")
        if arr[i] == target:
            steps.append(f"Found {target} at index {i}")
            return "\n".join(steps)
    #If target is found early then it will break, it adds target isn't found to the end of steps
    steps.append(f"{target} not found in the list.") 
    return "\n".join(steps)

# Gradio Interface generated by ChatGPT
with gr.Blocks() as demo:
    gr.Markdown("# Linear Search Visualizer\nEnter a list and a target to see each step of the search.")
    arr_input = gr.Textbox(label="Enter list of numbers (integers only)", placeholder="Example: 1, 2, 3, 4, 5 or 1,2,3,4,5")
    target_input = gr.Textbox(label="Enter target number (integers only)", placeholder="Example: 4")
    output = gr.Textbox(label="Search Steps", lines=12)
    search_button = gr.Button("Run Linear Search")
    search_button.click(
        fn=linear_search_visual,
        inputs=[arr_input, target_input],
        outputs=[output]
    )

demo.launch()